version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - pgsql
      - db_migration

  db_migration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_migration
    restart: "on-failure"
    depends_on:
      - pgsql
    env_file: .envs/app.env
    command: sh -c "python -m alembic upgrade head"

  pgsql:
    image: postgres:16.0-alpine3.18
    container_name: psql
    env_file:
      - .envs/db.env 
    ports:
      - "5432:5432" 
    volumes:
      - /fastapi-blog/postgresql/data:/var/lib/postgresql/data
    restart: always
