version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - psql


  psql:
    image: postgres:16.0-alpine3.18
    container_name: psql
    env_file:
      - .envs/db.env 
    ports:
      - "5432:5432" 
    volumes:
      - /fastapi-blog/postgresql/data:/var/lib/postgresql/data
    restart: always 


