# Your tests secrets

[app]
jwt_secret = "SECRET"

[http_server]
host = "http://test"

## Name of your test user
[db]
user = "test"
password = "12345qwerty"
name = "test"
host = "localhost"
port = 5433


